"""empty message

Revision ID: acd04b2ad6c1
Revises: c3457e2d7e45
Create Date: 2019-01-01 14:52:16.534833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'acd04b2ad6c1'
down_revision = 'c3457e2d7e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rw_language',
    sa.Column('language_id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('code', mysql.CHAR(length=2), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('localname', sa.String(length=50), nullable=False),
    sa.Column('queryurl', sa.String(length=255), nullable=True),
    sa.Column('hastranslation', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('haslexical', mysql.TINYINT(display_width=1), nullable=False),
    sa.PrimaryKeyConstraint('language_id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rw_language')
    # ### end Alembic commands ###
