"""empty message

Revision ID: c3457e2d7e45
Revises: 
Create Date: 2018-12-31 17:07:23.169497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3457e2d7e45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rw_rank',
    sa.Column('rank_id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('threshold', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.PrimaryKeyConstraint('rank_id')
    )
    op.create_table('rw_role',
    sa.Column('role_id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('rw_subscription',
    sa.Column('subscription_id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_table('rw_user',
    sa.Column('user_id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('salt', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('lastlogin', sa.TIMESTAMP(), nullable=True),
    sa.Column('lastloginattempt', sa.TIMESTAMP(), nullable=True),
    sa.Column('failedloginattempts', mysql.INTEGER(display_width=11), server_default=sa.text('0'), nullable=False),
    sa.Column('remembertoken', sa.String(length=100), nullable=True),
    sa.Column('voided', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rw_user')
    op.drop_table('rw_subscription')
    op.drop_table('rw_role')
    op.drop_table('rw_rank')
    # ### end Alembic commands ###
