"""empty message

Revision ID: cbf12ed86a32
Revises: acd04b2ad6c1
Create Date: 2019-01-01 15:03:14.408202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbf12ed86a32'
down_revision = 'acd04b2ad6c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rw_entry',
    sa.Column('entry_id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('media', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.PrimaryKeyConstraint('entry_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rw_entry')
    # ### end Alembic commands ###
