"""empty message

Revision ID: fe0dc57f45fd
Revises: cbf12ed86a32
Create Date: 2019-01-01 17:10:55.450256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe0dc57f45fd'
down_revision = 'cbf12ed86a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rw_searchrecord',
    sa.Column('search_id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('query', sa.String(length=100), nullable=False),
    sa.Column('suggest', sa.String(length=100), nullable=True),
    sa.Column('iterations', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('results', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('timetaken', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('remoteaddr', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('search_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rw_searchrecord')
    # ### end Alembic commands ###
